#    Copyright 2020 Leonardo Andres Morales

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

include:
  - project: 'masterleros/bash-devops-libs'
    ref: develop
    file: '/pipelines/gitlab/.gcp-template.yml'
  - project: 'masterleros/bash-devops-libs'
    ref: develop
    file: '/pipelines/gitlab/.base-template.yml'

variables:
  DEVOPS_LIBS_DIR: "${CI_PROJECT_DIR}/"
  DEVOPS_LIBS_BRANCHES_DEFINITION: "feature/*:DEV fix/*:DEV develop:INT release/*:UAT bugfix/*:UAT master:PRD hotfix/*:PRD"
  GOOGLE_APPLICATION_CREDENTIALS: "${CI_PROJECT_DIR}/credentials/credential.json"

stages:
  - Prepare
  - Provision
  - Build
  - Deploy
  - Test
  - Promote

My Prepare Job:
  stage: Prepare
  extends: .gcp-template.docker
  script:
    - do.import gcp.storage
    - do.gcp.storage.createBucket ${GCP_PROJECT_ID} ${GCP_PROJECT_ID}-terraform regional us-central1

My Provision Job:
  stage: Provision
  extends: .gcp-template.terraform-docker
  variables:
    TERRAFORM_DIR: "${CI_PROJECT_DIR}/terraform"    
  script:
    - export TF_VAR_project_id=${GCP_PROJECT_ID}
    - do.terraform.createBackEndGCP ${TERRAFORM_DIR} ${GCP_PROJECT_ID}-terraform gitlab-test
    - do.terraform.init ${TERRAFORM_DIR}
    - do.terraform.apply ${TERRAFORM_DIR}

My MVN Build Job:
  stage: Build
  image: maven:latest
  script:
    - mvn -version
  tags:
    - docker

My NODE Build Job:
  stage: Build
  image: node:latest  
  script:
    - node --version
  tags:
    - docker    

My Deploy Job:
  stage: Deploy
  extends: .gcp-template.docker
  script:
    - do.import utils
    - do.utils.showTitle "Deploying to the below instances"
    - gcloud --project ${GCP_PROJECT_ID} compute instances list
    - do.utils.showTitle "Hey I was deployed! =D"

My Test Job:
  stage: Test
  extends: .base-template.docker
  script:
    - do.import utils
    - do.utils.showTitle "Hey! I'm testing something here!"
    
My Promote Job:
  stage: Promote
  extends: .base-template.docker
  script:
    - do.import utils gitlab
    - do.utils.showTitle "Promoting Code to master!"
    - export
    - do.utils.showTitle ${CI_PROJECT_URL}
    - do.gitlab.promoteToBranch master
